import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import ProgressProvider from "@/lib/providers/ProgressProvider";
import ToastProvider from "@/lib/providers/ToastProvider";
import Sidebar from "@/components/sidebar/Sidebar";

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Undefined Hotel | Temukan Hotel Terbaik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${jost.className}`}>
        <ProgressProvider>
          <Sidebar>
            <ToastProvider>{children}</ToastProvider>
          </Sidebar>
        </ProgressProvider>
      </body>
    </html>
  );
}
